/**
 * RASID data spine - canonical TypeScript types.
 *
 * These types are the human-readable source of truth. The JSON Schema files in
 * `schemas/` are the machine-enforced mirror, and `npm run validate` checks the
 * data in `data/` against them. If you change a type here, change the matching
 * schema in the same commit.
 *
 * Honesty rule (spec section 0.2): every field that could be guessed instead of
 * observed carries a `provenance`. Unknown is `null` + `provenance: "unknown"`,
 * never a plausible default.
 */

export type Provenance =
  | "official" // stated on the organisation's own site/announcement
  | "reported" // aggregator site or student reports; treat as approximate
  | "inferred" // derived from past cycles; must be labelled in UI
  | "unknown";

export type Tier = "S" | "A" | "B" | "C";

export type Sector =
  | "gov"
  | "semi_gov"
  | "bank"
  /**
   * DEVIATION FROM SPEC section 3.1: added.
   * Investment houses, brokerages and insurers are not banks. Folding them in
   * blunts the sector filter, and the filter is how the user narrows 116
   * organisations down to the ones worth reading.
   */
  | "finance"
  | "tech"
  | "health"
  | "industrial"
  | "consulting"
  | "startup";

export type SourceType =
  | "careers_page"
  | "announcement_page"
  | "rss"
  | "portal"
  | "email"
  /**
   * DEVIATION FROM SPEC section 3.1: added.
   * A bare homepage, with no careers or training path known yet. Most of the
   * COOP-PDF import is this. Calling a site root a "careers_page" would be the
   * quiet kind of lie this project is built to avoid.
   */
  | "site_root";

/**
 * Where a record came into the database. Kept so that a verified record and an
 * imported one can never be confused in a report.
 */
export type ImportSource =
  | "spec" // the original RASID build specification
  | "coop_pdf_2021" // the circulated COOP directory pdf, ~2020-2021, unverified
  | "manual" // added by hand during a session, with a stated reason
  | null;

export type ApplyMethod = "portal" | "email" | "hrdf" | "linkedin_manual";

/**
 * Every stored link carries how we came to believe in it.
 *
 * A URL is never generated by analogy. `example.com/careers` working is not
 * evidence that `other.com/careers` exists. Only two provenances are legal
 * here, and "inferred" is deliberately not one of them:
 *
 *   "official" - the page was opened and read, and it is what it claims to be.
 *                Requires `verifiedAtISO` and `verifiedNote`.
 *   "reported" - a lead taken from a document or a third party, never opened.
 *                `verifiedAtISO` stays null and the pipeline skips it.
 */
export type LinkProvenance =
  /** The page was opened and read, and it is what it claims to be. */
  | "official"
  /** A lead from a document or a third party. Never opened. */
  | "reported"
  /**
   * An email address, not a page. There is nothing to open, so it can never
   * become "official" and it is permanently reported-strength. It is excluded
   * from the manualCheckUrl count and the fetch pipeline never touches it.
   * Legal in `applyVia` only.
   */
  | "email_channel";

export interface VerifiedLink {
  url: string;
  /**
   * "email_channel" is structurally excluded here, not merely discouraged:
   * only `applyVia` can hold one, so a mail address can never leak into a
   * fetchable source or into the link the user taps.
   */
  provenance: Exclude<LinkProvenance, "email_channel">;
  /** When the page was actually opened and read. null means never opened. */
  verifiedAtISO: string | null;
  /**
   * What was seen there. Required once verified, and it must carry the page's
   * real title plus a phrase read on the page. Without both, the link is
   * "reported", not "official".
   */
  verifiedNote?: string;
}

/**
 * How a source has to be fetched to yield text.
 *
 * "static"  - plain HTTP. The default, and the only mode a source may hold
 *             without someone deciding otherwise.
 * "browser" - rendered in headless Chromium because the page paints itself
 *             with JavaScript and static extraction provably returns nothing.
 *
 * Nothing is promoted to "browser" automatically. A source earns it only after
 * a static run has demonstrably failed on it, and the total is capped
 * (MAX_BROWSER_SOURCES): if more than a handful need a browser, the problem is
 * the choice of sources, not the fetcher.
 */
export type RenderMode = "static" | "browser";

export interface Source extends VerifiedLink {
  type: SourceType;
  /**
   * Whether the page said, in its own words, that it is about cooperative
   * training — and not merely that it opened and was readable.
   *
   * "official" answers a narrower question than a reader expects: the page was
   * opened, read, and is what it claims to be. A company homepage claiming to
   * be a company homepage passes that honestly, and most watched sources are
   * exactly that. But an audit found sixty-one of them presented with the same
   * confidence as the handful that actually carry a co-op announcement, so the
   * distinction is now stored rather than left to be inferred from a note, and
   * the interface says which it is looking at.
   */
  coopConfirmed?: boolean;
  checkFrequencyHours: number;
  renderMode: RenderMode;
  /**
   * Try the browser path again in CI, and only there.
   *
   * Set on a source whose rendering failed for want of machine resources
   * rather than for any reason on the site's side: a runner container is
   * roomier than a laptop, so the same page may well render there. A success
   * in CI promotes the source to "browser" for good and writes down why.
   */
  browserRetryInCI?: boolean;
  /** Why renderMode is not the default, in one line. Written by the collector. */
  renderModeNote?: string;
}

/**
 * Spec deviation, deliberate.
 *
 * This was 8, written when collection ran on a cloud runner where every
 * browser launch cost a minute of somebody's quota. Collection now runs on the
 * owner's own machine, because many Saudi government sites refuse a US
 * address, and there Chromium is already installed and the run is unattended.
 * The cap still exists so the browser stays a decision rather than a default,
 * but it is no longer priced as if it were rare.
 *
 * Raised again to 60 once each organisation began to be watched on every
 * channel it publishes rather than on the first link that answered: more
 * sources, and a fair share of Saudi portals paint themselves with script.
 * Going over is no longer fatal — the collector reads what fits and records the
 * rest as unread, which is visible in the app.
 */
export const MAX_BROWSER_SOURCES = 60;

/** Thin and unchanged for this many runs is worth surfacing. ~10 days at 6h. */
export const SILENT_THIN_RUNS = 40;

/** Below this the extract is suspiciously short, though still usable. */
export const THIN_CHARS = 200;

export interface ApplyVia {
  method: ApplyMethod;
  /** URL or email address. */
  target: string;
  /** `email_channel` whenever method is "email", and only then. */
  provenance: LinkProvenance;
  /** When the channel was confirmed at its source. Always null for email. */
  verifiedAtISO: string | null;
  note?: string;
}

export interface HistoricalWindow {
  /** e.g. "الفصل الثاني 1447" */
  seasonLabel: string;
  openedISO: string | null;
  closedISO: string | null;
  provenance: Provenance;
}

export interface ZeroCoursesRule {
  /** null = the organisation has never published a rule either way. */
  value: true | false | null;
  provenance: Provenance;
  /** Exact published wording. Required whenever value === true. */
  quote?: string;
  sourceUrl?: string;
}

export interface Stipend {
  amountSAR: number | null;
  provenance: Provenance;
  note?: string;
}

export interface Organisation {
  /** slug, e.g. "sdaia" */
  id: string;
  nameAr: string;
  nameEn: string;
  sector: Sector;
  /** ["الرياض"] etc. Empty = nationwide/unknown. */
  city: string[];
  tier: Tier;

  // THE THREE DECISION FIELDS
  requiresZeroCourses: ZeroCoursesRule;
  /** CS / cybersecurity / IT present in the published major list. */
  acceptsUserMajor: boolean | null;
  /** HRDF product is "التدريب التعاوني", not "تطوير الخريجين". */
  offersCoopProduct: boolean | null;

  // SUPPORTING
  stipend: Stipend;
  flexibility: "high" | "medium" | "low" | "unknown";
  intakeSize: "large" | "medium" | "small" | "unknown";
  /** How much you actually learn. 1-5, or null when unrated. */
  trainingQuality: 1 | 2 | 3 | 4 | 5 | null;

  // SOURCES
  sources: Source[];

  /**
   * DEVIATION FROM SPEC section 3.1: nullable.
   * The spec types this as a required `ApplyVia`, but section 4 forbids
   * inventing values for unverified fields. Most seed organisations have no
   * confirmed application channel yet, so `null` means "not verified" and the
   * validator reports it as coverage debt rather than letting a guessed URL in.
   */
  applyVia: ApplyVia | null;

  /**
   * DEVIATION FROM SPEC section 3.1: nullable, for the same reason as applyVia.
   * One tap for the user to verify manually. When null the UI must say the link
   * is not verified yet - it must not fall back to a search engine guess.
   *
   * This is the link the user personally taps, so it is held to the highest
   * bar in the codebase: it may only ever hold an opened-and-confirmed page.
   * The validator rejects a `reported` lead here, unlike in `sources`.
   */
  manualCheckUrl: VerifiedLink | null;

  // HISTORY (drives prediction, never presented as fact)
  historicalWindows: HistoricalWindow[];

  /** Free text shown in the detail sheet. */
  notes?: string;

  /**
   * Where this record entered the database. Kept so a hand-verified record and
   * a bulk import can never be read as the same thing in a report.
   */
  importSource: ImportSource;
}

/**
 * Aggregators are scanned for *any* co-op announcement and are not
 * organisations, so they live in `data/aggregators.json` with their own shape.
 */
export interface AggregatorSource {
  id: string;
  nameAr: string;
  link: VerifiedLink | null;
  /**
   * Some aggregators are reachable only by writing to a person. The platform
   * can exist and be unpublished, which is exactly the Taif field-training
   * case: the link is requested from the college, not found on the web.
   */
  applyVia: ApplyVia | null;
  /** Ranking hint for the pipeline when the same announcement appears twice. */
  weight: "highest" | "high" | "normal";
  checkFrequencyHours: number;
  note?: string;
}

/**
 * The audit trail of the link-verification rounds, in `data/verification.json`.
 *
 * Negative results are the point of this file. Recording "I looked for SABIC's
 * training page and the careers site has no training section" stops the next
 * round from repeating the search, and it is what makes the counts at the end
 * of `npm run validate` honest: verified, failed, still unknown.
 */
export interface VerificationAttempt {
  /** Organisation or aggregator id. */
  targetId: string;
  checkedAtISO: string;
  /** What was actually opened. null when nothing plausible was found to open. */
  urlTried: string | null;
  outcome:
    | "verified" // opened, and it is a real careers/training page
    | "rejected" // opened, but it is a generic page, not what we need
    | "not_found" // searched, found no candidate page to open at all
    | "unreachable"; // the page would not load: DNS, timeout, block
  /** What was seen, in one line. Required. */
  note: string;
}

export type OpportunityStatus =
  | "open"
  | "closing_soon"
  | "closed"
  | "announced_not_open"
  | "expired"
  /**
   * DEVIATION FROM SPEC section 3.2: added.
   * An announcement that published no dates at all. The spec's five states all
   * assert something about the window, and "open" would be the assertion we
   * have the least right to make: a page can name a programme without ever
   * saying when it takes applications. The home screen must not show this in
   * "مفتوح الآن".
   */
  | "unknown";

export type Product =
  | "coop"
  | "graduate_dev"
  | "professional_experience"
  | "unknown";

export type OpportunityFlag =
  | "few_seats" // seats <= 5
  | "closing_in_48h"
  | "exact_major_match" // cybersecurity / SOC analyst named directly
  | "no_course_condition" // published conditions contain no zero-courses rule
  | "has_stipend"
  | "wrong_product" // it is تطوير الخريجين - user is not eligible yet
  | "first_time_seen" // this org has never posted a co-op before
  | "needs_manual_review" // classifier failed twice; never drop it silently
  /**
   * The page this came from no longer shows it.
   *
   * Not the same as closed, and the difference matters: a closed window was
   * announced as closing, while this one simply stopped being visible. The
   * record used to be deleted outright in that situation, silently, which
   * cost a real open window with a relevance of 95 in an audit. It is kept
   * and marked instead, because "it disappeared" is information he needs —
   * the page may have been redesigned, or the deadline may have passed
   * without the page ever saying so.
   */
  | "vanished_from_source"
  /**
   * The page carries other announcements this record does not describe.
   *
   * The collector keeps exactly one record per source, so a careers page
   * listing four programmes produces one and hides three. Fixing that properly
   * means letting one page yield several records, which changes how a record
   * is identified. Until then the limit is stated on the card, so he opens the
   * page instead of trusting a list that is quietly partial.
   */
  | "more_on_page";

export interface Opportunity {
  /** hash of orgId + title + firstSeenISO */
  id: string;
  orgId: string;
  titleAr: string;
  detectedISO: string;
  firstSeenISO: string;
  lastConfirmedISO: string;

  status: OpportunityStatus;

  opensISO: string | null;
  closesISO: string | null;
  /** Umm al-Qura, shown alongside Gregorian. */
  closesHijri: string | null;

  product: Product;
  /** As published. */
  majors: string[];
  seats: number | null;
  stipendSAR: number | null;
  durationWeeks: number | null;
  cities: string[];

  /** 0-100. null only when classification failed and the record is queued. */
  relevanceScore: number | null;
  /** One Arabic sentence, from the classifier. */
  relevanceReason: string;

  /**
   * DEVIATION FROM SPEC section 3.2: added, and the most consequential field
   * in the record for this user.
   *
   * The classifier already extracts whether the page states a zero-courses or
   * full-time condition, and the exact wording behind it. The spec's
   * Opportunity had nowhere to keep either, so both were being thrown away -
   * leaving the one rule that decides whether he can take the placement as an
   * opinion rather than a quote. Kept here so a disagreement about a phrase
   * like "انتظام كلي" is settled by reading the sentence.
   */
  statesZeroCoursesRule: boolean;
  /** The exact published wording. null when no such rule was stated. */
  zeroCoursesQuote: string | null;
  flags: OpportunityFlag[];

  sourceUrl: string;
  applyUrl: string | null;
  /** <= 400 chars, for the user to read himself. */
  rawExcerpt: string;
}

export type HealthState = "healthy" | "degraded" | "broken";

/**
 * What the last successful fetch of a source looked like, in
 * `data/snapshots.json`.
 *
 * Spec section 5.2 hashes the extracted main text so the classifier only sees a
 * page when it has actually changed. Committing the hash to git also answers a
 * question logs cannot: when did this page last change, and how often does it?
 * `lastChangedISO` is the honest basis for predicting a window, in place of the
 * guesswork the UI is forbidden to present as fact.
 */
export interface SourceSnapshot {
  sourceUrl: string;
  orgId: string;
  /** SHA-256 of the extracted main text. null until a fetch succeeds. */
  contentHash: string | null;
  /**
   * A short hash per block of the page, so the next run can tell *which* part
   * moved rather than only that something did.
   *
   * Spec 5.3 asks for the changed block to be what the classifier sees. Without
   * this the whole page was hashed and then the first 6000 characters were sent
   * — so on a long portal the model was handed the top of the page while the
   * announcement sat further down, returned "not an announcement", and the
   * record was dropped with nothing flagged for review. A silent miss on the
   * one event the app exists to catch.
   */
  blockHashes?: string[];
  extractedChars: number | null;
  /** Readability, or the noisier stripped-body fallback. Readers should know. */
  extractionMethod: "readability" | "body_fallback" | null;
  firstSeenISO: string;
  /** When the hash last differed from the stored one. */
  lastChangedISO: string | null;
  /**
   * Consecutive runs where the extract was thin AND the hash did not move.
   *
   * A thin source that also goes silent may be a page we are not really
   * reading. It may equally be a training page with nothing on it, which is
   * the normal state outside an application window. At a six-hour cron,
   * SILENT_THIN_RUNS is about ten days: long enough that the quiet is worth
   * a look, and it stays a warning, because CI should fail on broken code and
   * not on an external site having nothing to say.
   */
  thinRuns: number;
  /**
   * The classifier could not judge this text and the source is still owed a
   * verdict. The hash is kept, so a later change is still detectable, but the
   * next run classifies it again instead of skipping it as unchanged. Without
   * this, one failed call would bury a source until the page happened to move.
   */
  pendingClassification: boolean;
}

export interface SourceHealth {
  sourceUrl: string;
  orgId: string;
  lastAttemptISO: string;
  lastSuccessISO: string | null;
  consecutiveFailures: number;
  lastError: string | null;
  /**
   * DEVIATION FROM SPEC section 3.3, on the owner's instruction: the spec put
   * degraded at >1 failure, which showed a source that had already failed once
   * as green. Any failure is now degraded; >5 is still broken.
   */
  state: HealthState;
}

/**
 * The Umm al-Qura date for a Gregorian instant, which spec 5 asks to be shown
 * beside the Gregorian one.
 *
 * This is a conversion, not an estimate. `islamic-umalqura` is the Umm al-Qura
 * calendar as shipped in ICU — the same table the Saudi civil calendar is
 * printed from — so this is not the arithmetic Hijri approximation that was
 * refused earlier as a guess. If a runtime were built without full ICU the
 * format would silently fall back to another calendar, so the output is checked
 * for digits and discarded when it looks wrong: a wrong deadline is the one
 * error this application must never make.
 *
 * It lives here, with the types and no imports, because both the collector and
 * the browser need it and the browser must not pull in the pipeline.
 */
export function hijriOf(iso: string | null): string | null {
  if (iso === null) return null;
  const at = new Date(iso);
  if (Number.isNaN(at.getTime())) return null;
  try {
    const text = new Intl.DateTimeFormat("ar-SA-u-ca-islamic-umalqura", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }).format(at);
    // ar-SA already ends the year with "هـ", so nothing is appended here.
    return /[0-9٠-٩]/.test(text) ? text : null;
  } catch {
    return null;
  }
}

/**
 * The last instant of a published deadline, in Riyadh.
 *
 * Application dates are published as days — `YYYY-MM-DD` — and `Date.parse`
 * reads a bare day as midnight UTC. That made "closes 15 October" expire at
 * three in the morning Riyadh time on the fifteenth, so the app spent the whole
 * of a window's final day insisting it was over. A deadline day is open until
 * it ends, and it ends where the user is. A full timestamp, if a page ever
 * publishes one, is taken exactly as given.
 */
const RIYADH_OFFSET_MS = 3 * 60 * 60 * 1000;

export function endOfDeadline(iso: string): number {
  return /^\d{4}-\d{2}-\d{2}$/.test(iso)
    ? Date.parse(`${iso}T23:59:59.999Z`) - RIYADH_OFFSET_MS
    : Date.parse(iso);
}

/** The first instant of a published day, read the same way. */
export function startOfDay(iso: string): number {
  return /^\d{4}-\d{2}-\d{2}$/.test(iso)
    ? Date.parse(`${iso}T00:00:00.000Z`) - RIYADH_OFFSET_MS
    : Date.parse(iso);
}

/**
 * The window state a record is in *now*, from the dates it published.
 *
 * This is deliberately a function of `(dates, now)` and nothing else, and it
 * lives here so both the collector and the browser can call it. The status used
 * to be computed once, at classification time, and stored — which meant a
 * window that opened the following week never became "open", because the page
 * had not changed and so was never re-read. An audit found a window that had
 * been open for ten days and closed the next day still filed under
 * "أُعلن ولم يفتح", with no alert ever sent. A value that depends on the clock
 * cannot be cached against a change in the page.
 *
 * A graduate-development programme is never open here whatever its dates: it is
 * not the product this application tracks, and spec 8.5 forbids the state.
 */
export function statusFor(
  o: Pick<Opportunity, "opensISO" | "closesISO" | "product" | "flags">,
  now: number = Date.now(),
): OpportunityStatus {
  if (o.product === "graduate_dev") return "unknown";
  if (o.flags.includes("needs_manual_review")) return "unknown";

  const opens = o.opensISO === null ? null : startOfDay(o.opensISO);
  const closes = o.closesISO === null ? null : endOfDeadline(o.closesISO);

  if (closes !== null && closes < now) return "closed";
  if (opens !== null && opens > now) return "announced_not_open";
  if (closes !== null && closes - now <= 48 * 60 * 60 * 1000) return "closing_soon";
  if (opens !== null || closes !== null) return "open";
  return "unknown";
}

/**
 * A value that cannot be displayed without saying where it came from.
 *
 * Spec 8.2 requires that no field reaches a screen without its provenance
 * travelling with it, and until now that was enforced by a script and by
 * discipline. Discipline is not a guarantee: `acceptsUserMajor` and
 * `offersCoopProduct` are `boolean | null` with no provenance anywhere in the
 * type, and the interface rendered them as confident green and red chips. An
 * audit found them and it was right to.
 *
 * Wrapping the value makes the compiler the enforcement. A display function
 * that takes `Attested<T>` cannot be handed a bare `T`, so a field with no
 * recorded provenance has to be marked `"unknown"` explicitly, in code, where a
 * reader can see the gap — rather than passing silently as fact.
 */
export interface Attested<T> {
  value: T;
  provenance: Provenance;
  /** The published wording, where there is one. */
  quote?: string;
  sourceUrl?: string;
}

/**
 * State the provenance of a value that has none recorded.
 *
 * Deliberately verbose to write. Every call is a place where the dataset does
 * not know something the interface is about to show, and it should be as
 * visible in the source as it is on the screen.
 */
export const unattested = <T>(value: T): Attested<T> => ({ value, provenance: "unknown" });

/** A value whose provenance the dataset does record. */
export const attested = <T>(value: T, from: ZeroCoursesRule | Stipend): Attested<T> => ({
  value,
  provenance: from.provenance,
  quote: "quote" in from ? from.quote : undefined,
  sourceUrl: "sourceUrl" in from ? from.sourceUrl : undefined,
});
